// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'gooey.events', kind: "module", path: './gooey/events.html', attributes: []},
{name: 'gooey.rasterization', kind: "module", path: './gooey/rasterization.html', attributes: []},
{name: 'gooey.rasterization.Rasterizer', kind: "interfacedeclaration", path: './gooey/rasterization/Rasterizer.html', attributes: []},
{name: 'gooey', kind: "module", path: './gooey.html', attributes: []},
{name: 'gooey.ImageFormat', kind: "enumdeclaration", path: './gooey/ImageFormat.html', attributes: []},
{name: 'gooey.Surface', kind: "classdeclaration", path: './gooey/Surface.html', attributes: []},
{name: 'gooey.Surface.dimensions', kind: "functiondeclaration", path: './gooey/Surface.dimensions.html', attributes: ["property", "const"]},
];
