name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - name: Cache Blend2D Artifacts (Posix)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: actions/cache@v2
        with:
          path: lib/blend2d
          key: ${{ runner.os }}-blend2d-${{ hashFiles('lib/blend2d/build/**/*.*') }}
          restore-keys: |
            ${{ runner.os }}-blend2d-
      - name: Build Documentation
        run: make docs
      - name: GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2.1.2
        with:
          target_branch: gh-pages
          build_dir: docs
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
